### ISSUE TITLE
AIBlacklist suggestion

### ISSUE THREAD

**Issue by joshboston723** [Moffein/RiskyMod#10]
Shipping Request Form should also be blacklisted since it absolutely does nothing for enemies, while it still spawns in a broken multishop that you can interact with and stacks with your own Shipping Forms.

**Comment by Moffein** [comment]
Wasn't aware that this item is available for enemies. I'll add it to the default blacklist.

**Comment by Moffein** [comment]
Added Shipping Request Form and Regenerating Scrap to the default blacklist (though I believe Scrap already doesn't get given to enemies). Will be live in the next update.
