### ISSUE TITLE
ShareSuite Compatibility with Commencement Changes

### ISSUE THREAD

**Issue by Poultron** [Moffein/RiskyMod#11]
Currently the pillars scale their item drops per-player in Multiplayer, which makes sense, but is not compatible with ShareSuite's overrides. I haven't tested Combat Shrines, but I assume they are the same.

**Comment by Moffein** [comment]
Thanks for letting me know, I'll look into this.

**Comment by Moffein** [comment]
Fixed it on my end, this will be in the next update.
