### ISSUE TITLE
Safer Spaces now at 7% per stack

### ISSUE THREAD

**Issue by PollyEdaline** [Moffein/RiskyMod#15]
This change is mentioned in the 0.6.0 patch notes as a possible change, but I believe it was not actually in place before. This change is not mentioned in the full notes. Unsure if this is intentional or not. (for the record, I am in favor of the change)

**Comment by Moffein** [comment]
I've been playing with Safer Spaces to try to get a feel for it, and I currently don't think it needs that nerf since the cooldown is considerable compared to the effectiveness of stacking Tougher Times.

**Comment by Poultron** [comment]
Thinking about it some more, any time I have Safer Spaces in a run, I tend to hardly notice the cooldown, especially combined with the ridiculous power of the Opal. It's possible that the real issue there is the Opal, though, which could perhaps do with a tuning-down.

**Comment by Moffein** [comment]
I've found Safer Spaces is a pretty character-specific choice. Mobile ranged characters like Huntress benefit a lot from it, while melee characters and more stationary characters like Enforcer get more use out of Tougher Times, which is a good design for a Void item.

Opal definitely has a huge effect for a White item. In Vanilla it's a nice fix for how the game gets really oneshotty, but with this mod's survivability changes, it ends up being overkill.

**Comment by Poultron** [comment]
That's fair, actually. I've been playing a lot of Huntress and Acrid, but haven't had many runs with Safer Spaces in my Acrid testing. Enforcer definitely benefits a lot more from being able to ablate chip damage through Tougher Times compared to Safer Spaces, and Acrid similarly would prefer to protect his Regenerative buff.
