### ISSUE TITLE
[Bug] Disabling Void Locus Changes in the config file does not return Void Fog

### ISSUE THREAD

**Issue by physixcat** [Moffein/RiskyMod#24]
As it says in the title. Despite changing that setting to false, there is still no Void Fog in the Locus when interacting with the Deep Void. Unsure if maybe I missed another setting specifically for that, or if the config is bugged.

**Comment by Moffein** [comment]
Core Modules got moved to the top of the config in the previous update, but the old config slots were left over and are nonfunctional. Make sure you're modifying the right one. The next update will give the config a big overhaul and split it into multiple files for ease of readability, so a similar issue may arise then.
