### ISSUE TITLE
[suggestion] making weaken better

### ISSUE THREAD

**Issue by Littleevo** [Moffein/RiskyMod#26]
having the functions of the utilities swapped makes little sense when weaken isn't a good debuff to begin with. maybe the primary's healing function can be removed and instead put into weaken. making directive disperse a one-time heal for little risk and bramble volley into a higher heal but higher risk alternative.

**Comment by Moffein** [comment]
Weaken is fine as-is, -30 armor is a teamwide 17% damage boost at worst and a 25% damage boost against bosses, on top of REX's naturally high DPS. Main purpose of choosing the alt shift is either if you want to further boost your already-high damage output, or if you're using alt skills that don't have an HP requirement to activate.
