### ISSUE TITLE
(Suggestion) Tweak Void Survivor corrupted mode

### ISSUE THREAD

**Issue by Tymmey** [Moffein/RiskyMod#29]
I noticed how the corrupted mode is sometimes useless or not fitting the gameplay situation.

Would it be possible, similar to normal primary, to make the corrupted handbeam also a main state, so that using secondary will not interrupt it.
Also I noticed, that the interruption and time loss from using the special skill to replenish corruption takes too long.
Somehow getting 25% while losing 10% already seems useless. Would be nice, to havethis also not interrupt the handbeam and be a little bit faster...

This is not necessary and basicaly just a stupid idea
If you wann go further... maybe make corruption loss based on skill use...
1s primary = 1%
secondary = 10%
utility = 25% 
or something like this.

thanks guys!

**Comment by Moffein** [comment]
I'll take a look at the Corrupted Special and Skill Multitasking while Corrupted.
Probably will leave Corruption drain as-is since I like the time-limited aspect of it.

**Comment by Tymmey** [comment]
Oh man, you're the best, thanks mate!
