### ISSUE TITLE
Captain Beacon Changes - More granular config options?

### ISSUE THREAD

**Issue by JardonKern** [Moffein/RiskyMod#30]
I really dig the new cooldown system for captain's beacons, but I'm really not a fan of the new beacon reworks (resupply and hack).
Would you consider splitting the Beacon Changes config into Beacon Cooldown and Beacon Reworks? Or whatever works.

**Comment by Moffein** [comment]
Sure thing. I'll probably add a "Enable Rework" and "Add Cooldown" option for each individual beacon in the next update.

**Comment by JardonKern** [comment]
Thanks bunches.
