### ISSUE TITLE
Bandit special passives didnt work??

### ISSUE THREAD

**Issue by Fongkelyj** [Moffein/RiskyMod#31]
![image](https://user-images.githubusercontent.com/85260918/167094766-58cf9e1c-b9ea-443b-b578-7f4495dec561.png)
[LogOutput.log](https://github.com/Moffein/RiskyMod/files/8638586/LogOutput.log)

my profile code:
tjqZuIMwFr

**Comment by Moffein** [comment]
Late response, but the bug was caused by some compatibility issues with Ancient Scepter that ended up getting fixed.
