### ISSUE TITLE
[Incompatability] Standalone Ancient Scepter doesn't play nice with some reworked skills.

### ISSUE THREAD

**Issue by Coffe-e** [Moffein/RiskyMod#37]
As the title says, the Scepter versions of some skills (As of testing, Commando Suppressive fire and Nade were affected) are bugged, and simply behave like the normal skill, but have a placeholder scepter name for the skill such as: "COMMANDO_SPECIAL_SCEPTER_NAME" or something of the like. I wouldn't be surprised if this was intended/a couldn't-be-bothered issue, as scepter compatibility is always asked for. I couldn't seem to upload an image of the issue, but I could probably get one to you over discord (TEA#9790). Here's the log from testing, in case it's needed.
[LogOutput.log](https://github.com/Moffein/RiskyMod/files/10108332/LogOutput.log)

**Comment by Moffein** [comment]
Thanks for catching that! The skills work as intended, I just forgot to set their name properly. I'll fix it up.
