### ISSUE TITLE
Bosses_Drop_Items dropping boss items 100% of the time

### ISSUE THREAD

**Issue by breadguy69** [Moffein/RiskyMod#4]
I couldn't find a github for this mod and you're not in any of the discords I'm in so this is the closest I could find to let you know about this issue. Anyway yeah, boss items are dropping 100% of the time with my settings of 93% blank chance and 7% yellow chance (and 0% of everything else) with your bosses drop items mod. Nothing showed up in the log other than the vanilla chat notification of me picking up the boss item, but I can send if you need. I am using WolfoQOL mod with the tp drop chance for yellow items set to 0%, but I'm pretty sure bosses were dropping their items directly 100% of the time even without that.

**Comment by Moffein** [comment]
Gonna take a look at this.

**Comment by Moffein** [comment]
Closed, turns out the "Tele Bosses Always Drop Greens" setting was causing the issue.
