### ISSUE TITLE
Isn't Repulsion Armor Plating just bad? Shouldn't it be buffed? [Suggestion]

### ISSUE THREAD

**Issue by BrokenDoop** [Moffein/RiskyMod#47]
Forgive me if my logic is kind of wrong about this, but 5 "armor" (blocking 5 damage) seems kind of outclassed by the Bison Steak, Topaz Brooch and the Personal Shield Generator (even more now since it gates HP damage).

_Also the reason I'm quoting "armor" is because the wiki says it's not actually increasing the armor stat but decreasing the damage by x amount after it does the actual armor check, if I'm reading that correctly._

Since other items increase you're hp/shield/barrier by way more than 5 the only time Repulsion Armor Plating is effective is when the added hp/shield/barrier from other items is depleted by barrages of attacks or DOT effects, since that added hp/shield/barrier is effectively 'blocking' the damage to your base health.

The issue is that for the amount of times you need to stack it for it to be useful you could have gotten items that give you more hp/shield or replenish you're hp/barrier faster which is more effective at preventing damage, especially late game.

And because you need to stack it so much it essentially has no synergy with the health/barrier/shield items.
Unless I'm wrong about all this?

I'm not sure what change would be the best but I have a few "ideas", though I'm not sure what's actually possible to implement.
These suggestions may sound over complex but just increasing the value of "armor" would either make it too good early game or not fix the problems by increasing it too little.

  1. You could add a percentile "armor" increase with each level making it better late game, stacks add more percentage. (could also increase with every "levels worth of hp" instead giving it synergy with the changed Bison Steak)
  2. You could increase the "armor" given heavily but every certain amount of hits (ignoring damage from DOT effects) temporarily disables one stack (minor delay before another stack can be disabled to prevent your "armor" being shredded instantly) and puts it on a short cooldown (the amount of hits needed could also depend on the damage dealt equal to a percent of your health before the reduction is calculated), the cooldown ignores incoming damage. 
  3. Similar to the first suggestion you could add a percentile increase but for every certain amount of hp/shield/barrier you have full instead, giving it insane synergy with all those other items.

Please let me know if I'm delusional.

**Comment by Moffein** [comment]
Repulsion Armor is pretty underrated. Burn DoT is capped at some small percentage of your health per tick, so even lategame a single plate can completely negate 1 stack of burn damage. It also has decent effectiveness against Wisps and Templars due to their low per-shot damage, though I'd imagine less so when looping.
Overall I think it's fine to leave as-is.
