### ISSUE TITLE
No Config File

### ISSUE THREAD

**Issue by CerbsUp** [Moffein/RiskyMod#51]
Bro theres no config file for this mod and it just wont work i really want this mod so please fix this bug
Fornow i mark it as Deprecated.

And btw im talking about the ScrapLauncherReload Mod.

**Comment by Moffein** [comment]
ScrapLauncherReload has no config options. Are there any options you are looking for?

I've tested the mod on a fresh profile, and can confirm it's working. If you are using any other mods that modify MUL-T's Scrap Launcher, those mods might be conflicting with this. It would help if you could send me your BepInEx logfile (r2modman -> Settings -> Locations -> Browse Profile Folder -> BepInEx/LogOutput.log)
