### ISSUE TITLE
Minor incompatibility issues with "GoldenCoastPlus" and "FlatItemBuff"

### ISSUE THREAD

**Issue by Aaron00000** [Moffein/RiskyMod#52]
Despite not mentioning any changes to the Lost Seer's Lenses, enabling RiskyMod somehow prevents FlatItemBuff's changes to the Lost Seer's Lenses from applying. Also, the changes RiskyMod makes to Titans/Aurelionite can conflict with changes GoldenCoastPlus makes to Aurelionite, perhaps a separate toggle for Aurelionite could be added in RiskyMod?

**Comment by Moffein** [comment]
I can add a separate toggle for the Aurelionite.
For the FlatItemBuff incompatibility, could you boot your game up to the main menu and post your LogOutput.log file here?
The file can be  found via r2modman -> Settings -> Locactions -> Browse Profile Folder, inside the BepInEx folder.

**Comment by Aaron00000** [comment]
[LogOutput.log](https://github.com/Moffein/RiskyMod/files/13419358/LogOutput.log)

Might not hurt to check and see if similar issues with other items may crop up. If it's happening with stuff that shouldn't be affected by the mod, may well happen with items actually affected by RiskyMod.

**Comment by Moffein** [comment]
If you can, export your mod profile as a file via r2modman, and post it here as well.
Will take a look when I get the chance.

**Comment by Aaron00000** [comment]
Did a bit more testing. On a fresh profile (with only the configs ported over from my standard profile), there isn't a conflict with the Lenses. Oddly enough however, on my main profile the Lenses' change won't take place if RiskyMod is on, but will go through if RiskyMod is off. 

Profile code since Github won't accept the profile format: 018bef2c-7b9a-2f2e-7289-767333e375a2

**Comment by Moffein** [comment]
I've done some testing, and found that disabling the Hunter's Harpoon, Leeching Seed, and Ben's Raincoat from FlatItemBuff seems to fix it. What was happening was the mod was crashing early-on into loading, so any changes that were supposed to run after the problem-sections ended up not being run.

I'm not sure what the exact cause is, but if you would like to test which changes work/don't, you can check your LogOutput.log, CTRL+F "FlatItemBuff", and see if there's any big error messages when the mod loads along with if the error shows any associated item change at the bottom. You can also check for errors with RiskyMod by searching for "RiskyMod:", as the mod is designed to report errors and continue loading even if problems arise.

In the meantime, I'll be adding in the Aurelionite config.

**Comment by Aaron00000** [comment]
Looks like I'd forgotten to turn those changes off back when I first installed RiskyMod, everything else was already off. Thanks for the help.
