### ISSUE TITLE
[Bug] Bandit Alternate Special "Rack 'Em Up" is Buggy In Multiplayer

### ISSUE THREAD

**Issue by floofytail22** [Moffein/RiskyMod#58]
As the title says, Bandit's alt. special "Rack 'Em Up" seems to have odd audio/visual feedback in multiplayer. The alt. special projectiles spawn from the center of the other player's body, with no sound. Oddly enough though, Goobo Jr. had correct VFX and SFX. Gummy Bandit would fire 6 rapid shots from the actual gun, with sound effects. 

The only mods installed besides RiskyMod/Tweaks/Fixes/etc. are Debugging Toolkit/Plains and Local Multiplayer Testing. 

https://github.com/user-attachments/assets/a69cb0b4-8838-446f-bd0b-675241d1c635

**Comment by Moffein** [comment]
Thanks for reporting this, I've uploaded a fix.
Let me know if it works!

**Comment by floofytail22** [comment]
Thanks for responding so quickly! Can confirm it now works, and the other changes you made to the skill feel great.
