### ISSUE TITLE
Potential Multiplayer Issues

### ISSUE THREAD

**Issue by kgDraco** [Moffein/RiskyMod#59]
For your awareness; I'm sorry this isn't a well tested report.
When RiskyMod v2.0.1 dropped, my friend and I hopped in multiplayer. The game was extremely laggy - getting into each other's lobbies were extremely delayed, and once we were in game, clicking to shoot practically paused the game for a few seconds (enemies could still hit and kill us). Additionally, Commando's new "Phase Lightning" was just Captain's M1 charging shot, as if it charged instantly. If there were more issues, I was not able to find them due to the unplayable lag/freezing effects. Restarting the game or disabling other mods did not fix the issues; internet connections were just fine and didn't explain lag/freeze.

If both my friend and I disabled RiskyMod then the issues went away. Unfortunately I didn't have a chance to test further or with your most recent version of the mod.

Did not have the other "Risky" mods at the time. Only other mods were EliteReworks and Actually_Faster (and their dependencies)

I'll update here next time I get a chance to further test multiplayer.

**Comment by kgDraco** [comment]
A possible explanation - I think the issue is that the standard procedure "update all mods" in Thunderstore updated RiskyMod but did not update the dependencies, so Thunderstore did not download the RiskyFixes or RiskyTweaks. I didn't know these other two mods existed until I read the RiskyMod changelog.

**Comment by Moffein** [comment]
Versions 2.0.0 to 2.0.2 had multiplayer syncing issues due to an unregistered skill, and was fixed in 2.0.3.
If the issues persist on the latest version let me know and have you and your friend upload your LogOutput.log file from r2modman -> Settings -> Locations -> Browse Profile Folder -> BepInEx/LogOutput.log, and I'll take a look at it.

**Comment by kgDraco** [comment]
had a chance to test and can confirm no more issues with multiplayer. Only changes made since initial post was updating currently installed mods. 
Thanks for this mod! Psyched to keep playing it post-DLC.
