### ISSUE TITLE
Incompatibility with MysticsItems

### ISSUE THREAD

**Issue by CounterfitCookie** [Moffein/RiskyMod#6]
Currently a change in RiskyMod which I cannot identify, doesn't allow the Wireless Voltmeter to proc off shield damage.

**Comment by Moffein** [comment]
Thanks for letting me know. I'll take a look at this.

**Comment by Moffein** [comment]
Managed to fix the issue, I'll be updating the Thunderstore version sometime soon. I also noticed that MysticItems' move-speed based items seem to break when any mod that uses RecalculateStatsAPI (this mod, most survivor mods, SS2) is loaded.
