### ISSUE TITLE
Ancient Scepter Acrid Skill issue

### ISSUE THREAD

**Issue by Coffe-e** [Moffein/RiskyMod#60]
After obtaining Ancient Scepter, Acrid's special reads as "CROCO_SPECIAL_NAME_RISKYMOD_SCEPTER", and no longer applies poison. Yet to do more testing, but messing with configs may be a temporary fix for anyone who is having this same issue.

**Comment by Moffein** [comment]
Thanks for reporting this, the issue has been fixed.
