### ISSUE TITLE
bug fix with PT-BR translation

### ISSUE THREAD

**Issue by ExPeerTT** [Moffein/RiskyMod#64]
bug fix with PT-BR translation
extract and replace the PT-BR folder in the folder:
AppData\Roaming\r2modmanPlus-local\RiskOfRain2\profiles\"your profile"\BepInEx\plugins\Risky_Lives-RiskyMod\Risky_Lives-RiskyMod\language

[PT-BR.zip](https://github.com/user-attachments/files/17091189/PT-BR.zip)

**Comment by Moffein** [comment]
Thanks, uploading fix.
