### ISSUE TITLE
A few bug reports

### ISSUE THREAD

**Issue by Progical** [Moffein/RiskyMod#65]
- Stone Titan fist count is only two instead of the listed three
- Safer Spaces cooldown is still 15 seconds instead of the listed 20
- Buffed Ignition Tank has a large spacing in item description

I've recently gotten into playing with this mod and I gotta say, I enjoy it very much. Especially with how customizable everything is with the many config options. I'll continue to report if I come across anything else.

One extra thing I wanted to comment on is the Engineer mobile turrets always sprinting. It's probably fine as is, though personally like HIFUEngineerTweaks implementation of greatly reducing the range from Engineer that allows them to sprint. It allows them to do it more often without it being _maybe_ too much, compared to the always active sprinting items whenever they move period.

I also wanted to say thank you for your contributions to the modding community, everything you do is much appreciated!

**Comment by Moffein** [comment]
Thanks for reporting these issues, I'll get around to fixing them.
As for the Stone Titan fist, it was nerfed from 3 to 2 some time back, but it seems I forgot to update the doc.
I haven't had a chance to play HIFU's Engineer tweaks so I don't have much of a point of reference to compare to, but I'm fine with the current state of Mobile Turrets as selecting them already removes a lot of the team utility you get from having Bungus turrets.
