### ISSUE TITLE
Help with translation

### ISSUE THREAD

**Issue by inkyarev** [Moffein/RiskyMod#66]
no idea how to contact you other than this
i can translate the mod into russian, although i have no clue how to actually do the translations(like what strings and where to get them etc)
i just have good knowledge of both languages(en and ru)

**Comment by Moffein** [comment]
Thanks for offering!

To create a new translation, get the language files from here:
https://github.com/Moffein/RiskyMod/tree/master/language/en
and replace the right side of each one with Russian.

To test the translation, go to r2modman->Swttings->Locations->Browse Profile Folder->BepInEx\plugins\Risky_Lives-RiskyMod\Risky_Lives-RiskyMod\language, and create a new RU folder to place your text files in.

Keep in mind that the game won't load if the formatting is wrong, but you can check that by using https://jsonlint.com/
The "Validate JSON" button will give an error, but as long as the colors look right it'll work.

**Comment by inkyarev** [comment]
alright, i started on the translations. do you have a discord or smth? i have some questions and i think it wouldnt be smart to dump them all here

**Comment by inkyarev** [comment]
@Moffein 
~~mention incase you didnt notice the prevoius comment~~

**Comment by inkyarev** [comment]
alright, i'm done. the questions were about context regarding some words, but even if i got the context wrong its not gonna be a big deal (for example whether "Permanent" keyword on the permanent beacons is supposed to be just a description or an effect name like "Agile" or "Ignite" since these are adjectives, but in vanilla translations they are instead converted to nouns(it sounds better in russian), and since it uses clsHealth, unlike other keywords that use clsUtility or clsDamage depending on what the keyword does and since the permanence isnt related to health i decided that its just a description and translated it as an adjective)
tried my best to keep the translations in line with the vanilla translations, improving some aspects where possible like honoring the uppercase letters of original ('Critical Strike' for example loses its uppercase letters) and others
the game loads up and translations are present
[RU.zip](https://github.com/user-attachments/files/17351198/RU.zip)

**Comment by Moffein** [comment]
Thanks!
For keywords, the cIsUtility/Damage/Health/etc is used to affect the keyword color.
The Permanent keyword uses the Health tag so that it can get a red color.

If you'd like to ask more questions , you can add me on Discord. My name is the same as on here.

**Comment by Moffein** [comment]
Added!
