### ISSUE TITLE
Shield gating True/False config setting does not seem to work

### ISSUE THREAD

**Issue by Ties-afk** [Moffein/RiskyMod#71]
Hi,

Setting the Shield Gating config setting to False in General > 01 Game Mechanics doesn't actually seem to turn of the Shield Gating mechanic (at least on our end)

The reason why I found out is because of the green Plankton item from the Supply Drop mod (https://thunderstore.io/package/Keroro1454/Supply_Drop/), which gives you +1 shield health on hit. This combined with the shield gating mechanic practically means you're immortal to anything but bosses for the rest of the run

Not a big deal, but wanted to report anyway.

**Comment by Moffein** [comment]
Thanks for reporting this, I've uploaded a fix.
