### ISSUE TITLE
Skill (description) Issue

### ISSUE THREAD

**Issue by gaforb** [Moffein/RiskyMod#8]
secondary changes overwrite the primary lang token, 1 line fix.

https://github.com/Moffein/RiskyMod/blob/504ebbb96607be1875d786411d44e13d418c26a4/RiskyMod/Survivors/Commando/CommandoCore.cs#L72

While you're at it, the loader skills and huntress' default blink could stand to have "agile" added to them if you already alter the lang files.

**Comment by Moffein** [comment]
Merged your pull request. I'll skip out on adding the Agile keyword to skills, since I personally feel it's bloat.
